HW1: linter setup and addressing issues
GenesisEducationKyiv/main-project-andrii0yerko pull request #2
Opened 2023-06-18 22:20 UTC by andrii0yerko

Details:
- Migrated the initial version of the project.
- Integrated `golangci-lint` into the project for improved code analysis.
- Implemented a corresponding GitHub Actions hook for automated checks.
- Addressed the issues identified by the linters across the project.

Feedback and advice are highly appreciated

2023-06-20 17:35 UTC, nazarsavorona commented on README.md
Need to clarify whether VS Code button is needed. Perhaps, it will be useful in some cases.

2023-06-20 17:37 UTC, nazarsavorona commented on README.md
> +Documentation for the endpoints can be found in [`docs/`](./docs/) folder. Postman collection provided in [`test/`](./test/) directory as well
I would place swagger specs in `api` folder.

2023-06-20 17:42 UTC, nazarsavorona commented on README.md
> +Documentation for the endpoints can be found in [`docs/`](./docs/) folder. Postman collection provided in [`test/`](./test/) directory as well
Perhaps, should take a look at [this](https://learning.postman.com/docs/integrations/available-integrations/github/) article. Seems like it is more automated.

2023-06-20 17:48 UTC, nazarsavorona commented on README.md
> +        docker run --rm -p 3333:3333 bitcoin-rate-app \
Should we pass this values through environment variables in Dockerfile, for example?

2023-06-20 18:00 UTC, nazarsavorona commented on cmd/bitcoin-rate-app/main.go
> +func main() {
Too much logic in `main.go`. Would be great to distribute it among other structs. You should only get your configuration and start an application using corresponding methods.

2023-06-20 18:19 UTC, nazarsavorona commented on configs/config.yaml
You have provided a configuration template, so you do not need to disclose your email credentials.

2023-06-20 18:22 UTC, nazarsavorona commented on pkg/core/coingeckorate.go
> +	cointTitle := strings.ToUpper(requester.Coin[:1]) + strings.ToLower(requester.Coin[1:])
You can do this in constructor, and you will have the desired format, so you do it once.

2023-06-20 18:29 UTC, nazarsavorona commented on pkg/core/controller.go
> +			err = sendErr
We will only have the last error, if any occurred. Should we gather any additional info, so the check `if sendErr != nil` is justified?

2023-06-20 18:35 UTC, nazarsavorona commented on pkg/core/filedb.go
> +func (db *FileDB) checkExists(value string) bool {
It's okay to check it here, but is it a better idea to check existence in our cache first, so we don't have to open a file once again?

2023-06-20 18:37 UTC, nazarsavorona commented on pkg/core/filedb.go
> +var ErrIsDuplicate = errors.New("is duplicate")
Great approach!

2023-06-20 18:38 UTC, nazarsavorona commented on test/bitcoin-rate-app.postman_collection.json
Still have a doubt whether it is a good idea to share this kind of files here.

2023-06-20 18:40 UTC, nazarsavorona commented on pkg/core/types.go
You should place interfaces in the place of their usage.

2023-06-20 18:42 UTC, nazarsavorona commented on pkg/core/http.go
> +	w.WriteHeader(http.StatusTeapot)
Could you please explain why this is useful?

2023-06-20 18:44 UTC, nazarsavorona commented on pkg/core/http.go
> +	if len(r.Method) > 0 && r.Method != http.MethodGet {
You can consider using [echo framework](https://github.com/labstack/echo), so you won't need to write such checks.

2023-06-20 18:47 UTC, nazarsavorona commented on pkg/core/http.go
> +	if err != nil {
I would write like this (without `/n`):
```
err := e.Controller.Subscribe(email)
if err != nil {
    // ...
}
```

2023-06-20 18:55 UTC, nazarsavorona commented
To enhance the clarity and maintainability of our codebase, I would like to propose a refactoring and reorganization of the `pkg/core` directory. By following a more modular approach and properly grouping related components, we can achieve a more intuitive and manageable structure.

2023-06-20 18:56 UTC, nazarsavorona commented
I wanted to express my appreciation for the great job you've done on the pull request. Your work is commendable, and it's clear that you put in a lot of effort.

While reviewing the pull request, I left a few comments regarding some minor edits. These suggestions are meant to further enhance the overall quality and clarity of the code. Please don't interpret them as major concerns or criticisms. I believe these edits will refine the code even further and make it even better.

2023-06-20 18:57 UTC, nazarsavorona requested changes
I wanted to express my appreciation for the great job you've done on the pull request. Your work is commendable, and it's clear that you put in a lot of effort.

While reviewing the pull request, I left a few comments regarding some minor edits. These suggestions are meant to further enhance the overall quality and clarity of the code. Please don't interpret them as major concerns or criticisms. I believe these edits will refine the code even further and make it even better.

2023-06-21 08:22 UTC, andrii0yerko commented on pkg/core/http.go
> +	if len(r.Method) > 0 && r.Method != http.MethodGet {
Thanks for the suggestion, I will take a look

2023-06-21 09:49 UTC, andrii0yerko commented on cmd/bitcoin-rate-app/main.go
> +func parseConfiguration() {
Good point. Got stuck to SetConfigName, and missed the existence of SetConfigFile

2023-06-21 09:53 UTC, closed without merging