HW3: SOLID, GRASP
GenesisEducationKyiv/main-project-andrii0yerko pull request #6
Opened 2023-07-01 21:17 UTC by andrii0yerko

2023-07-11 22:01 UTC, nazarsavorona requested changes
Great job! Left a few suggestions and questions. I believe it's not a big deal for you.

2023-07-11 22:37 UTC, andrii0yerko commented on pkg/core/service.go
> +	if s.receivers.Contains(receiver) {
IMO it's on the Service level, so I've moved it here. Not saving duplicates is a business requirement, not the infrastructure one

2023-07-11 22:45 UTC, andrii0yerko commented on pkg/core/emailformatter.go
> +	from string
Do you think it will be better to pass from email every time?

I did it assuming that every Sender has its own formatted, so I see no big problem with storing this property here

2023-07-11 22:47 UTC, andrii0yerko commented on pkg/core/service.go
>  func (s Service) ExchangeRate() (float64, error) {
Good point. Will try to do this in the next homework, after implementing the presentation layers

2023-07-11 22:48 UTC, andrii0yerko commented on pkg/http/handler.go
>  		return
Thanks for noticing. Will fix soon

2023-07-11 22:52 UTC, andrii0yerko commented on pkg/http/handler.go
>  	switch {
I don't think it's too complicated - 3 conditions, 1 line body in each

Rewriting it with ifs probably will introduce unneeded nesting

2023-07-11 22:53 UTC, andrii0yerko commented on pkg/model/subscriber.go
> +	if email == "" {
Good idea. There was no requirement to do this so, will take a look at my spare time

2023-07-11 22:54 UTC, andrii0yerko commented on pkg/rateclient/coingeckorate.go
> +		"https://api.coingecko.com/api/v3/simple/price?ids=%s&vs_currencies=%s",
Yeah, it should. Hope to fix it soon

2023-07-11 22:58 UTC, andrii0yerko commented
@nazarsavorona Thanks for your review! Nice points
Will try to fix it soon, but maybe during the next homework

2023-07-31 20:38 UTC, andrii0yerko commented on pkg/core/service.go
> +	sender := NewEmailSender(client, formatter)
враховано в майбутніх роботах

2023-07-31 21:13 UTC, merged